import CatalogImg from "../../assets/images/catalog-img.png";

export const BooksData = [
    {
        id: 1,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 2,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 0,
    },
    {
        id: 3,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 4,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 0,
    },
    {
        id: 5,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 6,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 7,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 8,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 9,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 10,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 11,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 0,
    },{
        id: 12,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 13,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 14,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 0,
    },
    {
        id: 15,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 16,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 17,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 18,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 19,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },
    {
        id: 20,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 0,
    },
    {
        id: 21,
        src: CatalogImg,
        alt: 'images1',
        bookTitle: 'Լռակյաց հիվանդը ...',
        desc: "Քոնելն ու Մարիաննան մեծացել են միեւնույն փոքր, պրովինցի...",
        price: "9500 ֏",
        count: 1,
    },

]